### PR TITLE
Check "static" callable for method existing in CallableResolver

### LINKED ISSUE #36: ReflectionException when trying to call a non-existent static method with an existing __callStatic method
### Bug Report

|    Q        |   A
|------------ | ------
| Version(s)  | 2.3.0

#### Summary

ReflectionException when trying to call a **non-existent static method** with an existing `__callStatic` method

#### Current behavior

ReflectionException: Method Xtreamwayz\PsrContainerMessenger\Container\TransportFactory::redis://localhost:6379/commandqueue() does not exist
Stack trace:
#0  …\vendor\php-di\invoker\src\CallableResolver.php(112)
https://github.com/PHP-DI/Invoker/blob/5a46b9d1d41af98e7a50e6a6edeb3bb207b9d59f/src/CallableResolver.php#L108-L118

#### How to reproduce

```php

namespace Xtreamwayz\PsrContainerMessenger\Container;

class TransportFactory {
    public static function __callStatic(string $dsn, array $arguments) {
        // return (new self($dsn))($arguments[0]);
    }
}

$invoker->call([TransportFactory::class, 'redis://localhost:6379/commandqueue']);
```

### PR DESCRIPTION
**Pull request by defaultpage**
Check if the callable represents a static call to a non-static method only for existing methods

Fixes https://github.com/PHP-DI/Invoker/issues/36

### CODE REVIEW

**Comment by mnapoli** [comment]
Not sure what this achieves, maybe adding a test could help?

**Comment by defaultpage** [comment]
> Not sure what this achieves, maybe adding a test could help?

The problem (#36) is that `CallableResolver` is called before `CallableReflection::create()` and **unexpected** `ReflectionException` from `CallableResolver` prevents calling `CallableReflection::create()`.

Because of this, the **expected** exception with an error message `Invoker\Test\InvokerTestStaticMagicMethodFixture::foo() is not a callable. A __call() or __callStatic() method exists but magic methods are not supported` **is not thrown** from the CallableReflection and user will see another error message `method ... doesn't exists`.

File: tests/InvokerTest.php [hunk 1]
```diff
@@ -73,6 +73,15 @@ public function cannot_invoke_magic_method()
         $this->invoker->call([new InvokerTestMagicMethodFixture, 'foo']);
     }
 
+    /**
+     * @test
+     */
+    public function cannot_invoke_static_magic_method()
+    {
+        $this->expectException(NotCallableException::class);
```
Comment (defaultpage) [inline tests/InvokerTest.php:82]: I added a test, but **without** next line:
```php
$this->expectExceptionMessage('Invoker\Test\InvokerTestMagicMethodFixture::foo() is not a callable. A __call() or __callStatic() method exists but magic methods are not supported.');
```

I can add this line if #40 will be merged.

Comment (mnapoli) [reply tests/InvokerTest.php:82]: 👍  #40 merged

**Comment by mnapoli** [comment]
Thanks!
